FROM quay.io/fedora/fedora:44

RUN dnf -y install \
        rpm-build \
        gcc \
        binutils \
        container-selinux \
        glib2-devel \
        pam-devel \
        selinux-policy-devel \
        systemd-rpm-macros \
        python3-devel \
        python3-build \
        python3-installer \
        python3-setuptools \
        python3-wheel \
    && dnf clean all
