"""Per-space host authentication support."""

from .protocol import (
    AUTHENTICATE,
    ERROR,
    MAX_PAYLOAD,
    REGISTER,
    RESULT,
    SESSION_CLOSE,
    SESSION_OPEN,
    TOKEN,
    LeaseSubject,
    MessageType,
    recv_frame,
    send_frame,
)
from .runtime import (
    GUEST_BINARIES,
    GUEST_NATIVE,
    GUEST_RUNTIME,
    GUEST_SOCKET,
    NATIVE_ROOT,
    RUNTIME_ROOT,
    AuthenticationRuntime,
    generate_pam_policy,
    generate_pam_session_policy,
    prepare_runtime,
    validate_guest_architecture,
    validate_native_bundle,
)
from .service import (
    AUTHENTICATION_TIMEOUT,
    PAM_WORKER,
    SESSION_ENV,
    AuthenticationService,
    LeaseConnection,
    LiveLease,
)
from .session import (
    client_session,
    process_parent,
    process_session_matches,
    process_start_time,
    session_for_pid,
    session_uid,
)


__all__ = [
    "AUTHENTICATE",
    "AUTHENTICATION_TIMEOUT",
    "ERROR",
    "GUEST_BINARIES",
    "GUEST_NATIVE",
    "GUEST_RUNTIME",
    "GUEST_SOCKET",
    "MAX_PAYLOAD",
    "NATIVE_ROOT",
    "PAM_WORKER",
    "REGISTER",
    "RESULT",
    "RUNTIME_ROOT",
    "SESSION_CLOSE",
    "SESSION_ENV",
    "SESSION_OPEN",
    "TOKEN",
    "AuthenticationRuntime",
    "AuthenticationService",
    "LeaseConnection",
    "LeaseSubject",
    "LiveLease",
    "MessageType",
    "client_session",
    "generate_pam_policy",
    "generate_pam_session_policy",
    "prepare_runtime",
    "process_parent",
    "process_session_matches",
    "process_start_time",
    "recv_frame",
    "send_frame",
    "session_for_pid",
    "session_uid",
    "validate_guest_architecture",
    "validate_native_bundle",
]
