#ifndef SPACES_PORTAL_INTERFACES_H
#define SPACES_PORTAL_INTERFACES_H

static const char portal_backend_xml[] =
    "<node><interface name=\"org.freedesktop.impl.portal.Account\"><method name=\"GetUserInforma"
    "tion\"><arg type=\"o\" name=\"handle\" direction=\"in\"/><arg type=\"s\" name=\"app_id\" direction="
    "\"in\"/><arg type=\"s\" name=\"window\" direction=\"in\"/><arg type=\"a{sv}\" name=\"options\" direc"
    "tion=\"in\"/><arg type=\"u\" name=\"response\" direction=\"out\"/><arg type=\"a{sv}\" name=\"result"
    "s\" direction=\"out\"/></method></interface><interface name=\"org.freedesktop.impl.portal.Cl"
    "ipboard\"><method name=\"RequestClipboard\"><arg type=\"o\" name=\"session_handle\" direction=\""
    "in\"/><arg type=\"a{sv}\" name=\"options\" direction=\"in\"/></method><method name=\"SetSelectio"
    "n\"><arg type=\"o\" name=\"session_handle\" direction=\"in\"/><arg type=\"a{sv}\" name=\"options\" "
    "direction=\"in\"/></method><method name=\"SelectionWrite\"><arg type=\"o\" name=\"session_handl"
    "e\" direction=\"in\"/><arg type=\"u\" name=\"serial\" direction=\"in\"/><arg type=\"h\" name=\"fd\" d"
    "irection=\"out\"/></method><method name=\"SelectionWriteDone\"><arg type=\"o\" name=\"session_h"
    "andle\" direction=\"in\"/><arg type=\"u\" name=\"serial\" direction=\"in\"/><arg type=\"b\" name=\"s"
    "uccess\" direction=\"in\"/></method><method name=\"SelectionRead\"><arg type=\"o\" name=\"sessio"
    "n_handle\" direction=\"in\"/><arg type=\"s\" name=\"mime_type\" direction=\"in\"/><arg type=\"h\" n"
    "ame=\"fd\" direction=\"out\"/></method><signal name=\"SelectionOwnerChanged\"><arg type=\"o\" na"
    "me=\"session_handle\" direction=\"out\"/><arg type=\"a{sv}\" name=\"options\" direction=\"out\"/><"
    "/signal><signal name=\"SelectionTransfer\"><arg type=\"o\" name=\"session_handle\" direction=\""
    "out\"/><arg type=\"s\" name=\"mime_type\" direction=\"out\"/><arg type=\"u\" name=\"serial\" direct"
    "ion=\"out\"/></signal><property name=\"version\" type=\"u\" access=\"read\"/></interface><interf"
    "ace name=\"org.freedesktop.impl.portal.Email\"><method name=\"ComposeEmail\"><arg type=\"o\" n"
    "ame=\"handle\" direction=\"in\"/><arg type=\"s\" name=\"app_id\" direction=\"in\"/><arg type=\"s\" n"
    "ame=\"parent_window\" direction=\"in\"/><arg type=\"a{sv}\" name=\"options\" direction=\"in\"/><ar"
    "g type=\"u\" name=\"response\" direction=\"out\"/><arg type=\"a{sv}\" name=\"results\" direction=\""
    "out\"/></method></interface><interface name=\"org.freedesktop.impl.portal.GlobalShortcuts\""
    "><method name=\"CreateSession\"><arg type=\"o\" name=\"handle\" direction=\"in\"/><arg type=\"o\" "
    "name=\"session_handle\" direction=\"in\"/><arg type=\"s\" name=\"app_id\" direction=\"in\"/><arg t"
    "ype=\"a{sv}\" name=\"options\" direction=\"in\"/><arg type=\"u\" name=\"response\" direction=\"out\""
    "/><arg type=\"a{sv}\" name=\"results\" direction=\"out\"/></method><method name=\"BindShortcuts"
    "\"><arg type=\"o\" name=\"handle\" direction=\"in\"/><arg type=\"o\" name=\"session_handle\" direct"
    "ion=\"in\"/><arg type=\"a(sa{sv})\" name=\"shortcuts\" direction=\"in\"/><arg type=\"s\" name=\"par"
    "ent_window\" direction=\"in\"/><arg type=\"a{sv}\" name=\"options\" direction=\"in\"/><arg type=\""
    "u\" name=\"response\" direction=\"out\"/><arg type=\"a{sv}\" name=\"results\" direction=\"out\"/></"
    "method><method name=\"ListShortcuts\"><arg type=\"o\" name=\"handle\" direction=\"in\"/><arg typ"
    "e=\"o\" name=\"session_handle\" direction=\"in\"/><arg type=\"u\" name=\"response\" direction=\"out"
    "\"/><arg type=\"a{sv}\" name=\"results\" direction=\"out\"/></method><method name=\"ConfigureSho"
    "rtcuts\"><arg type=\"o\" name=\"session_handle\" direction=\"in\"/><arg type=\"s\" name=\"parent_w"
    "indow\" direction=\"in\"/><arg type=\"a{sv}\" name=\"options\" direction=\"in\"/></method><signal"
    " name=\"Activated\"><arg type=\"o\" name=\"session_handle\" direction=\"out\"/><arg type=\"s\" nam"
    "e=\"shortcut_id\" direction=\"out\"/><arg type=\"t\" name=\"timestamp\" direction=\"out\"/><arg ty"
    "pe=\"a{sv}\" name=\"options\" direction=\"out\"/></signal><signal name=\"Deactivated\"><arg type"
    "=\"o\" name=\"session_handle\" direction=\"out\"/><arg type=\"s\" name=\"shortcut_id\" direction=\""
    "out\"/><arg type=\"t\" name=\"timestamp\" direction=\"out\"/><arg type=\"a{sv}\" name=\"options\" d"
    "irection=\"out\"/></signal><signal name=\"ShortcutsChanged\"><arg type=\"o\" name=\"session_han"
    "dle\" direction=\"out\"/><arg type=\"a(sa{sv})\" name=\"shortcuts\" direction=\"out\"/></signal><"
    "property name=\"version\" type=\"u\" access=\"read\"/></interface><interface name=\"org.freedes"
    "ktop.impl.portal.Inhibit\"><method name=\"Inhibit\"><arg type=\"o\" name=\"handle\" direction=\""
    "in\"/><arg type=\"s\" name=\"app_id\" direction=\"in\"/><arg type=\"s\" name=\"window\" direction=\""
    "in\"/><arg type=\"u\" name=\"flags\" direction=\"in\"/><arg type=\"a{sv}\" name=\"options\" directi"
    "on=\"in\"/></method><method name=\"CreateMonitor\"><arg type=\"o\" name=\"handle\" direction=\"in"
    "\"/><arg type=\"o\" name=\"session_handle\" direction=\"in\"/><arg type=\"s\" name=\"app_id\" direc"
    "tion=\"in\"/><arg type=\"s\" name=\"window\" direction=\"in\"/><arg type=\"u\" name=\"response\" dir"
    "ection=\"out\"/></method><signal name=\"StateChanged\"><arg type=\"o\" name=\"session_handle\" d"
    "irection=\"out\"/><arg type=\"a{sv}\" name=\"state\" direction=\"out\"/></signal><method name=\"Q"
    "ueryEndResponse\"><arg type=\"o\" name=\"session_handle\" direction=\"in\"/></method></interfac"
    "e><interface name=\"org.freedesktop.impl.portal.InputCapture\"><method name=\"CreateSession"
    "\"><arg type=\"o\" name=\"handle\" direction=\"in\"/><arg type=\"o\" name=\"session_handle\" direct"
    "ion=\"in\"/><arg type=\"s\" name=\"app_id\" direction=\"in\"/><arg type=\"s\" name=\"parent_window\""
    " direction=\"in\"/><arg type=\"a{sv}\" name=\"options\" direction=\"in\"/><arg type=\"u\" name=\"re"
    "sponse\" direction=\"out\"/><arg type=\"a{sv}\" name=\"results\" direction=\"out\"/></method><met"
    "hod name=\"CreateSession2\"><arg type=\"o\" name=\"session_handle\" direction=\"in\"/><arg type="
    "\"s\" name=\"app_id\" direction=\"in\"/><arg type=\"a{sv}\" name=\"options\" direction=\"in\"/><arg "
    "type=\"a{sv}\" name=\"results\" direction=\"out\"/></method><method name=\"Start\"><arg type=\"o\""
    " name=\"handle\" direction=\"in\"/><arg type=\"o\" name=\"session_handle\" direction=\"in\"/><arg "
    "type=\"s\" name=\"app_id\" direction=\"in\"/><arg type=\"s\" name=\"parent_window\" direction=\"in\""
    "/><arg type=\"a{sv}\" name=\"options\" direction=\"in\"/><arg type=\"u\" name=\"response\" directi"
    "on=\"out\"/><arg type=\"a{sv}\" name=\"results\" direction=\"out\"/></method><method name=\"GetZo"
    "nes\"><arg type=\"o\" name=\"handle\" direction=\"in\"/><arg type=\"o\" name=\"session_handle\" dir"
    "ection=\"in\"/><arg type=\"s\" name=\"app_id\" direction=\"in\"/><arg type=\"a{sv}\" name=\"options"
    "\" direction=\"in\"/><arg type=\"u\" name=\"response\" direction=\"out\"/><arg type=\"a{sv}\" name="
    "\"results\" direction=\"out\"/></method><method name=\"SetPointerBarriers\"><arg type=\"o\" name"
    "=\"handle\" direction=\"in\"/><arg type=\"o\" name=\"session_handle\" direction=\"in\"/><arg type="
    "\"s\" name=\"app_id\" direction=\"in\"/><arg type=\"a{sv}\" name=\"options\" direction=\"in\"/><arg "
    "type=\"aa{sv}\" name=\"barriers\" direction=\"in\"/><arg type=\"u\" name=\"zone_set\" direction=\"i"
    "n\"/><arg type=\"u\" name=\"response\" direction=\"out\"/><arg type=\"a{sv}\" name=\"results\" dire"
    "ction=\"out\"/></method><method name=\"Enable\"><arg type=\"o\" name=\"session_handle\" directio"
    "n=\"in\"/><arg type=\"s\" name=\"app_id\" direction=\"in\"/><arg type=\"a{sv}\" name=\"options\" dir"
    "ection=\"in\"/><arg type=\"u\" name=\"response\" direction=\"out\"/><arg type=\"a{sv}\" name=\"resu"
    "lts\" direction=\"out\"/></method><method name=\"Disable\"><arg type=\"o\" name=\"session_handle"
    "\" direction=\"in\"/><arg type=\"s\" name=\"app_id\" direction=\"in\"/><arg type=\"a{sv}\" name=\"op"
    "tions\" direction=\"in\"/><arg type=\"u\" name=\"response\" direction=\"out\"/><arg type=\"a{sv}\" "
    "name=\"results\" direction=\"out\"/></method><method name=\"Release\"><arg type=\"o\" name=\"sess"
    "ion_handle\" direction=\"in\"/><arg type=\"s\" name=\"app_id\" direction=\"in\"/><arg type=\"a{sv}"
    "\" name=\"options\" direction=\"in\"/><arg type=\"u\" name=\"response\" direction=\"out\"/><arg typ"
    "e=\"a{sv}\" name=\"results\" direction=\"out\"/></method><method name=\"ConnectToEIS\"><arg type"
    "=\"o\" name=\"session_handle\" direction=\"in\"/><arg type=\"s\" name=\"app_id\" direction=\"in\"/><"
    "arg type=\"a{sv}\" name=\"options\" direction=\"in\"/><arg type=\"h\" name=\"fd\" direction=\"out\"/"
    "></method><signal name=\"Disabled\"><arg type=\"o\" name=\"session_handle\" direction=\"out\"/><"
    "arg type=\"a{sv}\" name=\"options\" direction=\"out\"/></signal><signal name=\"Activated\"><arg "
    "type=\"o\" name=\"session_handle\" direction=\"out\"/><arg type=\"a{sv}\" name=\"options\" directi"
    "on=\"out\"/></signal><signal name=\"Deactivated\"><arg type=\"o\" name=\"session_handle\" direct"
    "ion=\"out\"/><arg type=\"a{sv}\" name=\"options\" direction=\"out\"/></signal><signal name=\"Zone"
    "sChanged\"><arg type=\"o\" name=\"session_handle\" direction=\"out\"/><arg type=\"a{sv}\" name=\"o"
    "ptions\" direction=\"out\"/></signal><property name=\"SupportedCapabilities\" type=\"u\" access"
    "=\"read\"/><property name=\"version\" type=\"u\" access=\"read\"/></interface><interface name=\"o"
    "rg.freedesktop.impl.portal.Notification\"><method name=\"AddNotification\"><arg type=\"s\" na"
    "me=\"app_id\" direction=\"in\"/><arg type=\"s\" name=\"id\" direction=\"in\"/><arg type=\"a{sv}\" na"
    "me=\"notification\" direction=\"in\"/></method><method name=\"RemoveNotification\"><arg type=\""
    "s\" name=\"app_id\" direction=\"in\"/><arg type=\"s\" name=\"id\" direction=\"in\"/></method><prope"
    "rty name=\"SupportedOptions\" type=\"a{sv}\" access=\"read\"/><signal name=\"ActionInvoked\"><ar"
    "g type=\"s\" name=\"app_id\"/><arg type=\"s\" name=\"id\"/><arg type=\"s\" name=\"action\"/><arg typ"
    "e=\"av\" name=\"parameter\"/></signal><property name=\"version\" type=\"u\" access=\"read\"/></int"
    "erface><interface name=\"org.freedesktop.impl.portal.Print\"><method name=\"PreparePrint\"><"
    "arg type=\"o\" name=\"handle\" direction=\"in\"/><arg type=\"s\" name=\"app_id\" direction=\"in\"/><"
    "arg type=\"s\" name=\"parent_window\" direction=\"in\"/><arg type=\"s\" name=\"title\" direction=\""
    "in\"/><arg type=\"a{sv}\" name=\"settings\" direction=\"in\"/><arg type=\"a{sv}\" name=\"page_setu"
    "p\" direction=\"in\"/><arg type=\"a{sv}\" name=\"options\" direction=\"in\"/><arg type=\"u\" name=\""
    "response\" direction=\"out\"/><arg type=\"a{sv}\" name=\"results\" direction=\"out\"/></method><m"
    "ethod name=\"Print\"><arg type=\"o\" name=\"handle\" direction=\"in\"/><arg type=\"s\" name=\"app_i"
    "d\" direction=\"in\"/><arg type=\"s\" name=\"parent_window\" direction=\"in\"/><arg type=\"s\" name"
    "=\"title\" direction=\"in\"/><arg type=\"h\" name=\"fd\" direction=\"in\"/><arg type=\"a{sv}\" name="
    "\"options\" direction=\"in\"/><arg type=\"u\" name=\"response\" direction=\"out\"/><arg type=\"a{sv"
    "}\" name=\"results\" direction=\"out\"/></method></interface><interface name=\"org.freedesktop"
    ".impl.portal.RemoteDesktop\"><method name=\"CreateSession\"><arg type=\"o\" name=\"handle\" dir"
    "ection=\"in\"/><arg type=\"o\" name=\"session_handle\" direction=\"in\"/><arg type=\"s\" name=\"app"
    "_id\" direction=\"in\"/><arg type=\"a{sv}\" name=\"options\" direction=\"in\"/><arg type=\"u\" name"
    "=\"response\" direction=\"out\"/><arg type=\"a{sv}\" name=\"results\" direction=\"out\"/></method>"
    "<method name=\"SelectDevices\"><arg type=\"o\" name=\"handle\" direction=\"in\"/><arg type=\"o\" n"
    "ame=\"session_handle\" direction=\"in\"/><arg type=\"s\" name=\"app_id\" direction=\"in\"/><arg ty"
    "pe=\"a{sv}\" name=\"options\" direction=\"in\"/><arg type=\"u\" name=\"response\" direction=\"out\"/"
    "><arg type=\"a{sv}\" name=\"results\" direction=\"out\"/></method><method name=\"Start\"><arg ty"
    "pe=\"o\" name=\"handle\" direction=\"in\"/><arg type=\"o\" name=\"session_handle\" direction=\"in\"/"
    "><arg type=\"s\" name=\"app_id\" direction=\"in\"/><arg type=\"s\" name=\"parent_window\" directio"
    "n=\"in\"/><arg type=\"a{sv}\" name=\"options\" direction=\"in\"/><arg type=\"u\" name=\"response\" d"
    "irection=\"out\"/><arg type=\"a{sv}\" name=\"results\" direction=\"out\"/></method><method name="
    "\"NotifyPointerMotion\"><arg type=\"o\" name=\"session_handle\" direction=\"in\"/><arg type=\"a{s"
    "v}\" name=\"options\" direction=\"in\"/><arg type=\"d\" name=\"dx\" direction=\"in\"/><arg type=\"d\""
    " name=\"dy\" direction=\"in\"/></method><method name=\"NotifyPointerMotionAbsolute\"><arg type"
    "=\"o\" name=\"session_handle\" direction=\"in\"/><arg type=\"a{sv}\" name=\"options\" direction=\"i"
    "n\"/><arg type=\"u\" name=\"stream\" direction=\"in\"/><arg type=\"d\" name=\"x\" direction=\"in\"/><"
    "arg type=\"d\" name=\"y\" direction=\"in\"/></method><method name=\"NotifyPointerButton\"><arg t"
    "ype=\"o\" name=\"session_handle\" direction=\"in\"/><arg type=\"a{sv}\" name=\"options\" direction"
    "=\"in\"/><arg type=\"i\" name=\"button\" direction=\"in\"/><arg type=\"u\" name=\"state\" direction="
    "\"in\"/></method><method name=\"NotifyPointerAxis\"><arg type=\"o\" name=\"session_handle\" dire"
    "ction=\"in\"/><arg type=\"a{sv}\" name=\"options\" direction=\"in\"/><arg type=\"d\" name=\"dx\" dir"
    "ection=\"in\"/><arg type=\"d\" name=\"dy\" direction=\"in\"/></method><method name=\"NotifyPointe"
    "rAxisDiscrete\"><arg type=\"o\" name=\"session_handle\" direction=\"in\"/><arg type=\"a{sv}\" nam"
    "e=\"options\" direction=\"in\"/><arg type=\"u\" name=\"axis\" direction=\"in\"/><arg type=\"i\" name"
    "=\"steps\" direction=\"in\"/></method><method name=\"NotifyKeyboardKeycode\"><arg type=\"o\" nam"
    "e=\"session_handle\" direction=\"in\"/><arg type=\"a{sv}\" name=\"options\" direction=\"in\"/><arg"
    " type=\"i\" name=\"keycode\" direction=\"in\"/><arg type=\"u\" name=\"state\" direction=\"in\"/></me"
    "thod><method name=\"NotifyKeyboardKeysym\"><arg type=\"o\" name=\"session_handle\" direction=\""
    "in\"/><arg type=\"a{sv}\" name=\"options\" direction=\"in\"/><arg type=\"i\" name=\"keysym\" direct"
    "ion=\"in\"/><arg type=\"u\" name=\"state\" direction=\"in\"/></method><method name=\"NotifyTouchD"
    "own\"><arg type=\"o\" name=\"session_handle\" direction=\"in\"/><arg type=\"a{sv}\" name=\"options"
    "\" direction=\"in\"/><arg type=\"u\" name=\"stream\" direction=\"in\"/><arg type=\"u\" name=\"slot\" "
    "direction=\"in\"/><arg type=\"d\" name=\"x\" direction=\"in\"/><arg type=\"d\" name=\"y\" direction="
    "\"in\"/></method><method name=\"NotifyTouchMotion\"><arg type=\"o\" name=\"session_handle\" dire"
    "ction=\"in\"/><arg type=\"a{sv}\" name=\"options\" direction=\"in\"/><arg type=\"u\" name=\"stream\""
    " direction=\"in\"/><arg type=\"u\" name=\"slot\" direction=\"in\"/><arg type=\"d\" name=\"x\" direct"
    "ion=\"in\"/><arg type=\"d\" name=\"y\" direction=\"in\"/></method><method name=\"NotifyTouchUp\"><"
    "arg type=\"o\" name=\"session_handle\" direction=\"in\"/><arg type=\"a{sv}\" name=\"options\" dire"
    "ction=\"in\"/><arg type=\"u\" name=\"slot\" direction=\"in\"/></method><method name=\"ConnectToEI"
    "S\"><arg type=\"o\" name=\"session_handle\" direction=\"in\"/><arg type=\"s\" name=\"app_id\" direc"
    "tion=\"in\"/><arg type=\"a{sv}\" name=\"options\" direction=\"in\"/><arg type=\"h\" name=\"fd\" dire"
    "ction=\"out\"/></method><property name=\"AvailableDeviceTypes\" type=\"u\" access=\"read\"/><pro"
    "perty name=\"version\" type=\"u\" access=\"read\"/></interface><interface name=\"org.freedeskto"
    "p.impl.portal.ScreenCast\"><method name=\"CreateSession\"><arg type=\"o\" name=\"handle\" direc"
    "tion=\"in\"/><arg type=\"o\" name=\"session_handle\" direction=\"in\"/><arg type=\"s\" name=\"app_i"
    "d\" direction=\"in\"/><arg type=\"a{sv}\" name=\"options\" direction=\"in\"/><arg type=\"u\" name=\""
    "response\" direction=\"out\"/><arg type=\"a{sv}\" name=\"results\" direction=\"out\"/></method><m"
    "ethod name=\"SelectSources\"><arg type=\"o\" name=\"handle\" direction=\"in\"/><arg type=\"o\" nam"
    "e=\"session_handle\" direction=\"in\"/><arg type=\"s\" name=\"app_id\" direction=\"in\"/><arg type"
    "=\"a{sv}\" name=\"options\" direction=\"in\"/><arg type=\"u\" name=\"response\" direction=\"out\"/><"
    "arg type=\"a{sv}\" name=\"results\" direction=\"out\"/></method><method name=\"Start\"><arg type"
    "=\"o\" name=\"handle\" direction=\"in\"/><arg type=\"o\" name=\"session_handle\" direction=\"in\"/><"
    "arg type=\"s\" name=\"app_id\" direction=\"in\"/><arg type=\"s\" name=\"parent_window\" direction="
    "\"in\"/><arg type=\"a{sv}\" name=\"options\" direction=\"in\"/><arg type=\"u\" name=\"response\" dir"
    "ection=\"out\"/><arg type=\"a{sv}\" name=\"results\" direction=\"out\"/></method><property name="
    "\"AvailableSourceTypes\" type=\"u\" access=\"read\"/><property name=\"AvailableCursorModes\" typ"
    "e=\"u\" access=\"read\"/><property name=\"version\" type=\"u\" access=\"read\"/></interface><inter"
    "face name=\"org.freedesktop.impl.portal.Screenshot\"><method name=\"Screenshot\"><arg type=\""
    "o\" name=\"handle\" direction=\"in\"/><arg type=\"s\" name=\"app_id\" direction=\"in\"/><arg type=\""
    "s\" name=\"parent_window\" direction=\"in\"/><arg type=\"a{sv}\" name=\"options\" direction=\"in\"/"
    "><arg type=\"u\" name=\"response\" direction=\"out\"/><arg type=\"a{sv}\" name=\"results\" directi"
    "on=\"out\"/></method><method name=\"PickColor\"><arg type=\"o\" name=\"handle\" direction=\"in\"/>"
    "<arg type=\"s\" name=\"app_id\" direction=\"in\"/><arg type=\"s\" name=\"parent_window\" direction"
    "=\"in\"/><arg type=\"a{sv}\" name=\"options\" direction=\"in\"/><arg type=\"u\" name=\"response\" di"
    "rection=\"out\"/><arg type=\"a{sv}\" name=\"results\" direction=\"out\"/></method><property name"
    "=\"AvailableTargets\" type=\"u\" access=\"read\"/><property name=\"version\" type=\"u\" access=\"re"
    "ad\"/></interface><interface name=\"org.freedesktop.impl.portal.Settings\"><method name=\"Re"
    "adAll\"><arg type=\"as\" name=\"namespaces\" direction=\"in\"/><arg type=\"a{sa{sv}}\" name=\"valu"
    "e\" direction=\"out\"/></method><method name=\"Read\"><arg type=\"s\" name=\"namespace\" directio"
    "n=\"in\"/><arg type=\"s\" name=\"key\" direction=\"in\"/><arg type=\"v\" name=\"value\" direction=\"o"
    "ut\"/></method><signal name=\"SettingChanged\"><arg type=\"s\" name=\"namespace\" direction=\"ou"
    "t\"/><arg type=\"s\" name=\"key\" direction=\"out\"/><arg type=\"v\" name=\"value\" direction=\"out\""
    "/></signal><property name=\"version\" type=\"u\" access=\"read\"/></interface><interface name="
    "\"org.freedesktop.impl.portal.Wallpaper\"><method name=\"SetWallpaperURI\"><arg type=\"o\" nam"
    "e=\"handle\" direction=\"in\"/><arg type=\"s\" name=\"app_id\" direction=\"in\"/><arg type=\"s\" nam"
    "e=\"parent_window\" direction=\"in\"/><arg type=\"s\" name=\"uri\" direction=\"in\"/><arg type=\"a{"
    "sv}\" name=\"options\" direction=\"in\"/><arg type=\"u\" name=\"response\" direction=\"out\"/></met"
    "hod></interface><interface name=\"org.freedesktop.impl.portal.Request\"><method name=\"Clos"
    "e\"></method></interface><interface name=\"org.freedesktop.impl.portal.Session\"><method na"
    "me=\"Close\"></method><signal name=\"Closed\"></signal><property name=\"version\" type=\"u\" acc"
    "ess=\"read\"/></interface></node>"
    ;

#endif
